name: Build Feeds
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC diario

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Show .gitignore and check-ignore
        run: |
          echo "=== .gitignore ==="
          [ -f .gitignore ] && cat .gitignore || echo "(no .gitignore)"
          echo "=== git check-ignore data/ and *.xml ==="
          git check-ignore -v data || true
          git check-ignore -v "*.xml" || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build script (fail if no files)
        run: |
          set -euo pipefail
          python scripts/build_feeds.py
          echo "=== LIST AFTER SCRIPT ==="
          ls -la
          ls -la data || (echo "FALTA carpeta data" && exit 1)
          # Asegura que existan archivos y pesen > 0
          test -s data/venezuela.xml || (echo "venezuela.xml vacío o no existe" && exit 1)
          test -s data/panama.xml    || (echo "panama.xml vacío o no existe" && exit 1)
          test -s data/dominicana.xml || (echo "dominicana.xml vacío o no existe" && exit 1)
          echo "=== HEAD XMLs ==="
          head -n 20 data/*.xml || true

      - name: Debug git status (antes de add)
        run: |
          echo "=== GIT STATUS (pre-add) ==="
          git status
          echo "=== DIFF (working) ==="
          git diff --name-only
          
      - name: Commit generated feeds
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git add -f data/*.xml || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto build feeds: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git pull --rebase origin main || true
            git push origin HEAD:main
          fi
          
    - name: Final git status
      run: |
        git status
