name: Build Feeds
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC diario

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Detect branch and show repo info
        id: branch
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF=$GITHUB_BASE_REF"
          CURR_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "branch=$CURR_BRANCH" >> $GITHUB_OUTPUT
          echo "Current branch: $CURR_BRANCH"
          echo "=== .gitignore ==="
          [ -f .gitignore ] && cat .gitignore || echo "(no .gitignore)"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feed builder
        run: |
          set -euo pipefail
          python scripts/build_feeds.py
          # Stamp para forzar diff aunque el XML coincida byte a byte
          mkdir -p data
          date -u +"%Y-%m-%dT%H:%M:%SZ" > data/.build-stamp
          echo "=== LIST data ==="
          ls -la data
          echo "=== HEAD XMLs ==="
          head -n 25 data/*.xml || true

      - name: Commit & push (to current branch)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A || true
          git add -f data/*.xml data/.build-stamp || true

          echo "=== STAGED FILES ==="
          git diff --cached --name-only || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 2
          fi

          git commit -m "Auto build feeds: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          # Empuja a la rama realmente checkouteada
          BRANCH="${{ steps.branch.outputs.branch }}"
          echo "Pushing to $BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH"
