name: Build Feeds
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"   # 10:00 UTC diario

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Print repo info
        run: |
          echo "PWD=$(pwd)"
          git remote -v
          git branch -vv || true
          echo "=== .gitignore ==="
          [ -f .gitignore ] && cat .gitignore || echo "(no .gitignore)"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build script (fail hard if bad outputs)
        run: |
          set -euo pipefail
          python scripts/build_feeds.py
          echo "=== TREE AFTER SCRIPT ==="
          ls -la
          echo "=== DATA DIR ==="
          ls -la data || (echo "FALTA carpeta data" && exit 1)
          for f in venezuela.xml panama.xml dominicana.xml; do
            test -s "data/$f" || (echo "$f vacío o no existe" && exit 1)
            grep -q "<lastBuildDate>" "data/$f" || (echo "$f sin lastBuildDate" && exit 1)
          done
          echo "=== HEAD XMLs ==="
          head -n 25 data/*.xml || true

      - name: Show diffs BEFORE add
        run: |
          echo "=== GIT STATUS (working tree) ==="
          git status
          echo "=== DIFF (working) ==="
          git diff --name-only || true
          echo "=== check-ignore ==="
          git check-ignore -v data || true
          git check-ignore -v "*.xml" || true

      - name: Commit generated feeds (force add; rebase-safe push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A || true
          git add -f data/*.xml || true

          echo "=== STAGED FILES ==="
          git diff --cached --name-only || true

          if git diff --cached --quiet; then
            echo "No changes to commit (nada staged)."
            exit 2
          fi

          git commit -m "Auto build feeds: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          git pull --rebase origin main || true
          git push origin HEAD:main

      - name: Final status
        run: |
          git status
