name: Build Feeds (PR)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feeds
        run: |
          set -euo pipefail
          python scripts/build_feeds.py
          mkdir -p data
          date -u +"%Y-%m-%dT%H:%M:%SZ" > data/.build-stamp
          ls -la data
          head -n 25 data/*.xml || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feeds-bot
          title: "Auto build feeds"
          commit-message: "Auto build feeds: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          body: "Actualización diaria de XML (con lastBuildDate y build-stamp)."
          add-paths: |
            data/*.xml
            data/.build-stamp
          signoff: false
          delete-branch: true
