name: Build Feeds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"   # Todos los días a las 10:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # clona todo el historial
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run build script
        run: |
          python scripts/build_feeds.py

      - name: Commit generated feeds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Agrega TODO (no solo data/*.xml) para evitar el problema del glob.
          git add -A

          # Solo commitea si hay cambios staged
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto build feeds: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            # Evita non-fast-forward si corren builds seguidos
            git pull --rebase origin main || true
            git push origin HEAD:main
          fi

      - name: Show generated files
        run: |
          echo "=== LIST DATA DIR ==="
          ls -la data || ls -la
          echo "=== HEAD OF XMLs ==="
          for f in data/*.xml; do
            echo "---- $f ----"
            head -n 40 "$f" || true
          done

