name: DIAG Commit
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (current ref)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.ref_name }}

      - name: Detect branch
        id: branch
        run: |
          CURR_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "branch=$CURR_BRANCH" >> $GITHUB_OUTPUT
          echo "Current branch: $CURR_BRANCH"
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Write test file in data/
        run: |
          set -euo pipefail
          mkdir -p data
          echo "stamp $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > data/.diag-stamp
          ls -la data
          cat data/.diag-stamp

      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git add -f data/.diag-stamp || true
          echo "=== STAGED ==="
          git diff --cached --name-only || true
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 2
          fi
          git commit -m "DIAG: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BRANCH="${{ steps.branch.outputs.branch }}"
          echo "Pushing to $BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH"
